export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_OK = "AUTH_LOGIN_OK";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_OK = "AUTH_LOGOUT_OK";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_OK = "AUTH_REGISTER_OK";
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL";

export const AUTH_SEND_PASSWORD_RESET = "AUTH_SEND_PASSWORD_RESET";
export const AUTH_SEND_PASSWORD_RESET_OK = "AUTH_SEND_PASSWORD_RESET_OK";
export const AUTH_SEND_PASSWORD_RESET_FAIL = "AUTH_SEND_PASSWORD_RESET_FAIL";

export const AUTH_PASSWORD_RESET = "AUTH_PASSWORD_RESET";
export const AUTH_PASSWORD_RESET_OK = "AUTH_PASSWORD_RESET_OK";
export const AUTH_PASSWORD_RESET_FAIL = "AUTH_PASSWORD_RESET_FAIL";
